# Generated by Django 4.0 on 2023-02-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_room_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='recipient',
            new_name='owner',
        ),
    ]
