# Generated by Django 4.0 on 2023-02-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_recipient_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
